"""
Integration Test: E2E From HTML — Snapshot Test
=================================================
Exercises the ACTUAL pipeline template via _E2EPipelineRunner subclass.
Compares every output artifact against golden fixtures exactly.

  HTML fixture → localhost → _E2EPipelineRunner.run(jobs) →
  all 7 template steps → compare outputs vs golden fixtures.

Mock boundaries:
  1. HTML: served from localhost (deterministic).
  2. Search: skipped (_search_and_extract_influencers overridden).
  3. LLM: MOCK (returns 10 deterministic influencers).
  4. DDG: MOCK (empty, no network).
  5. needs_llm: PATCHED → True (force LLM mock to fire).

Golden fixtures regenerated by:
    PYTHONPATH="." python tests/integration/_bootstrap_e2e_golden.py

Run with:
    PYTHONPATH="." pytest tests/integration/test_e2e_from_html.py -v
"""

from __future__ import annotations

import http.server
import json
import re
import threading
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from config.schema import Influencer, Platform
from services.enrichment.CategoryProvenanceTagger import CategoryProvenanceTagger
from config.seed_schema import (
    SeedJob, SubCategory, Region, RegionCode, Difficulty,
)

from base_pipeline import BasePipelineRunner, GatherResult, JobOutcome
from services.audit.AuditService import AuditLog
from services.crawling.CrawlService import CrawlService
from services.extraction.HandleExtractionService import HandleExtractionService


# ── Paths ──

FIXTURE_HTML = Path(__file__).resolve().parent.parent / "fixtures" / "gymfluencers_uk_fitness.html"
GOLDEN_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "e2e_golden"


# ── Mock LLM Output ──

def _build_mock_influencers() -> list[Influencer]:
    return [
        Influencer(name="Joe Wicks", handles={Platform.Instagram: "thebodycoach"}),
        Influencer(name="Alex Beattie", handles={
            Platform.Instagram: "alex.beattie",
            Platform.TikTok: "alex.beattie",
        }),
        Influencer(name="Lucy Davis", handles={}),
        Influencer(name="Courtney Black", handles={
            Platform.Instagram: "courtneyblackfitness",
            Platform.TikTok: "courtneyblackfitness",
        }),
        Influencer(name="Michael Griffiths", handles={
            Platform.YouTube: "mac_griffiths",
        }),
        Influencer(name="Emma Storey-Gordon", handles={
            Platform.Instagram: "esgfitness",
            Platform.YouTube: "esgfitness",
        }),
        Influencer(name="Lisa Cross", handles={
            Platform.TikTok: "bblisacross",
        }),
        Influencer(name="Adam Maxted", handles={
            Platform.YouTube: "adammaxted2262",
        }),
        Influencer(name="Victoria Niamh", handles={
            Platform.TikTok: "victorianiamh",
        }),
        Influencer(name="Sean Casey", handles={}),
    ]


MOCK_INFLUENCERS = _build_mock_influencers()


# ── Local HTTP Server ──

class _FixtureHandler(http.server.SimpleHTTPRequestHandler):
    fixture_content: bytes = b""

    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(self.fixture_content)))
        self.end_headers()
        self.wfile.write(self.fixture_content)

    def log_message(self, format, *args):
        pass


def _start_server(html_bytes: bytes) -> tuple[http.server.HTTPServer, int]:
    _FixtureHandler.fixture_content = html_bytes
    server = http.server.HTTPServer(("127.0.0.1", 0), _FixtureHandler)
    port = server.server_address[1]
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server, port


# ── Pipeline Subclass ──

class _E2EPipelineRunner(BasePipelineRunner):
    """Concrete subclass for deterministic E2E snapshot testing."""

    def __init__(self, local_url: str, audit: AuditLog, **kwargs) -> None:
        super().__init__(name_resolution=False, **kwargs)
        self._local_url = local_url
        self._audit = audit

    async def _search_and_extract_influencers(
        self, jobs: list[SeedJob],
    ) -> GatherResult:
        job = jobs[0]

        crawl_svc = CrawlService(self._audit)
        pages = await crawl_svc.crawl_urls([
            (self._local_url, "site:gymfluencers.agency fitness influencers UK"),
        ])
        self._stats.record_crawl(
            pages, dropped=crawl_svc.dropped_count, retries=crawl_svc.retry_count,
        )

        handle_svc = HandleExtractionService(self._audit)

        async def mock_llm_extract(pages, platform, category_key, sub_name, region, year, sample_n=None):
            from config import OUTPUT_TOKENS_PER_INFLUENCER
            if not pages:
                return {}, 0, 0
            return {pages[0].url: list(MOCK_INFLUENCERS)}, 3800, len(MOCK_INFLUENCERS) * OUTPUT_TOKENS_PER_INFLUENCER

        with (
            patch("services.extraction.HandleExtractionService.needs_llm", return_value=True),
            patch(
                "services.extraction.LLMExtractionService.LLMExtractionService.extract",
                side_effect=mock_llm_extract,
            ),
        ):
            extract_result = await handle_svc.extract_all_handles(
                pages, platform=job.platform.value, category_key=job.category_key,
                sub_name=job.sub.sub_name, region=job.region.label, year="2026",
                direct_handles=[], sample_n=None,
            )
        self._stats.record_extraction(extract_result)

        from services.enrichment.NameToHandleService import NameToHandleService
        mock_search_client = MagicMock()
        mock_search_client.search_text.return_value = []
        mock_search_client.nr_query_template.return_value = '{name} Instagram YouTube TikTok'
        name_to_handle_svc = NameToHandleService(
            self._audit,
            search_client=mock_search_client,
            delay_seconds=0,
        )
        unique = name_to_handle_svc.resolve_cross_account_handles(
            extract_result.all_merged, platform=job.platform,
        )
        self._stats.record_enrichment(
            unique_count=len(unique),
            handles_filled=sum(1 for inf in unique if inf.handles),
            retries=name_to_handle_svc.retries, failures=name_to_handle_svc.failures,
        )

        CategoryProvenanceTagger.tag_from_job(
            influencers=unique,
            category_key=job.category_key,
            sub_name=job.sub.sub_name,
        )
        return GatherResult(
            influencers=unique,
            name_tracker=extract_result.name_tracker,
            job_outcomes=[JobOutcome(job=job, search_results=None, errored=None)],
        )

    async def _on_config_search_finished(self, job, search_results) -> None:
        pass

    def _report_mode(self) -> str:
        return "e2e-test"


# ── Helpers ──

def _strip_timestamps(text: str) -> str:
    """Remove timestamps so report comparisons are stable."""
    text = re.sub(r"\d{4}-\d{2}-\d{2}[T_]\d{2}[:\d]*\S*", "<TIMESTAMP>", text)
    text = re.sub(r"Generated: .*", "Generated: <TIMESTAMP>", text)
    return text


def _sort_records(records: list[dict]) -> list[dict]:
    """Sort a list of dicts by all values for stable comparison."""
    return sorted(records, key=lambda r: json.dumps(r, sort_keys=True))


def _normalize_urls(records: list[dict]) -> list[dict]:
    """Replace localhost:PORT with localhost:0 so random ports don't break snapshots."""
    out = []
    for r in records:
        r2 = dict(r)
        if "source_urls" in r2:
            r2["source_urls"] = [
                re.sub(r"127\.0\.0\.1:\d+", "127.0.0.1:0", u)
                for u in r2["source_urls"]
            ]
        out.append(r2)
    return out


def _load_golden(name: str):
    path = GOLDEN_DIR / name
    assert path.exists(), f"Golden fixture missing: {path}. Run _bootstrap_e2e_golden.py"
    return json.loads(path.read_text()) if name.endswith(".json") else path.read_text()


# ── E2E Snapshot Test ──

@pytest.mark.asyncio
async def test_e2e_from_html():
    """Snapshot test: run pipeline, compare every output against golden fixtures."""

    assert FIXTURE_HTML.exists(), f"HTML fixture not found: {FIXTURE_HTML}"
    html_bytes = FIXTURE_HTML.read_bytes()

    server, port = _start_server(html_bytes)
    local_url = f"http://127.0.0.1:{port}/gymfluencers_uk_fitness.html"

    try:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)

            with (
                patch("services.crawling.CrawlService.PAGES_DIR", tmp_path / "pages"),
                patch("services.extraction.LLMExtractionService.RAW_DIR", tmp_path / "raw"),
                patch("base_pipeline.RESULTS_DIR", tmp_path / "results"),
                patch("base_pipeline.AUDIT_DIR", tmp_path / "audit"),
            ):
                audit = AuditLog(tmp_path / "audit", "e2e_html_test")

                job = SeedJob(
                    platform=Platform.Instagram,
                    region=Region(code=RegionCode.UK, language="en", label="United Kingdom"),
                    category_key="FITNESS",
                    sub=SubCategory(
                        sub_name="Fitness", is_top_level=True,
                        search_prompt="fitness influencers", alt_search_terms=[],
                        known_sources=["gymfluencers.agency"], platform_notes="",
                        region_notes="", difficulty=Difficulty.EASY, strict_slugs=[],
                    ),
                )

                runner = _E2EPipelineRunner(local_url=local_url, audit=audit)
                seeds = await runner.run([job])

                # ── Compare against golden fixtures ──

                # Find run directory (results/<run_id>/)
                results_dir = tmp_path / "results"
                run_dirs = [d for d in results_dir.iterdir() if d.is_dir()]
                assert len(run_dirs) == 1, (
                    f"Expected 1 run directory, got {len(run_dirs)}"
                )
                run_dir = run_dirs[0]

                # 1. seeds.json
                actual_seeds = _sort_records(_normalize_urls(json.loads(
                    (run_dir / "seeds.json").read_text()
                )))
                expected_seeds = _sort_records(_normalize_urls(
                    _load_golden("seeds.json")
                ))
                assert actual_seeds == expected_seeds, (
                    f"seeds.json mismatch:\n"
                    f"  actual count: {len(actual_seeds)}\n"
                    f"  expected count: {len(expected_seeds)}"
                )

                # 2. unresolved_names.json
                actual_unresolved = _sort_records(_normalize_urls(json.loads(
                    (run_dir / "unresolved_names.json").read_text()
                )))
                expected_unresolved = _sort_records(_normalize_urls(
                    _load_golden("unresolved_names.json")
                ))
                assert actual_unresolved == expected_unresolved, (
                    f"unresolved_names.json mismatch:\n"
                    f"  actual count: {len(actual_unresolved)}\n"
                    f"  expected count: {len(expected_unresolved)}"
                )

                # 3. output.json (seeds as dicts)
                actual_output = _sort_records(_normalize_urls(
                    [s.to_dict() for s in seeds]
                ))
                expected_output = _sort_records(_normalize_urls(
                    _load_golden("output.json")
                ))
                assert actual_output == expected_output, (
                    f"output.json mismatch:\n"
                    f"  actual count: {len(actual_output)}\n"
                    f"  expected count: {len(expected_output)}"
                )

                # 4. report.md
                actual_report = _strip_timestamps((run_dir / "report.md").read_text())
                expected_report = _load_golden("report.md")
                assert actual_report == expected_report, "report.md content mismatch"

                # 5. validation_results
                actual_vr = {}
                for key, result in runner.validation_results.items():
                    if result:
                        actual_vr[key] = {
                            "pass_rate": result.pass_rate,
                            "found": sorted(result.found),
                            "missing": sorted(result.missing),
                            "expected": sorted(result.expected),
                        }
                expected_vr = _load_golden("validation_results.json")
                assert actual_vr == expected_vr, (
                    f"validation_results mismatch:\n"
                    f"  actual: {actual_vr}\n"
                    f"  expected: {expected_vr}"
                )

                # 6. Run directory has all files
                assert (run_dir / "seeds.json").exists()
                assert (run_dir / "unresolved_names.json").exists()

                # 7. Audit trail
                assert len(audit.entries) > 0, "Audit trail is empty"
                phases = {e.phase for e in audit.entries}
                assert "crawl" in phases, "Audit missing crawl entries"

    finally:
        server.shutdown()
