"""
QueryBuilder
=============
Generates DuckDuckGo search query strings from seed config.

Query types (3 total):
  1. Primary open:     {search_prompt} {platform} influencers list {year}
  2. Alt open:         {alt_term} {platform} influencers {region} {year}
  3. Site-targeted:    site:{source} {search_prompt} {platform} {year}

For non-Easy difficulty, all queries are prefixed with an inurl: OR clause
derived from the sub-category name to constrain results to relevant URL paths.

Formula per leaf (sub × platform × region):
  perms = 1 primary + len(altSearchTerms) alt + len(knownSources) site-targeted
"""

from __future__ import annotations
from dataclasses import dataclass
from enum import Enum

from config.seed_schema import Difficulty


class QueryType(str, Enum):
    """Type of search query generated by QueryBuilder."""
    PRIMARY_OPEN = "primary_open"        # Open web using main search prompt
    ALT_OPEN = "alt_open"                # Open web using alternate search terms
    SITE_TARGETED = "site_targeted"      # Scoped to a specific known source via site: operator


@dataclass
class SearchQuery:
    """A single search query with its type for audit logging."""
    query: str
    query_type: QueryType


class QueryBuilder:
    """Builds all search queries for a given seed job."""

    def __init__(
        self,
        sub_name: str,
        platform: str,
        region: str,
        year: str,
        search_prompt: str,
        alt_search_terms: list[str],
        known_sources: list[str],
        difficulty: Difficulty,
        inurl_slugs: list[str],
    ):
        self.sub_name = sub_name
        self.platform = platform
        self.region = region
        self.year = year
        self.search_prompt = search_prompt
        self.alt_search_terms = alt_search_terms
        self.known_sources = known_sources
        self.difficulty = difficulty
        self.inurl_slugs = inurl_slugs

    @property
    def _inurl_clause(self) -> str:
        """Build inurl: OR clause for strict search. Empty if no slugs defined."""
        if not self.inurl_slugs:
            return ""
        return " OR ".join(f"inurl:{s}" for s in self.inurl_slugs) + " "

    def build_all(self) -> list[SearchQuery]:
        """Generate all queries in execution order."""
        queries: list[SearchQuery] = []
        queries.extend(self._primary_open())
        queries.extend(self._alt_open())
        queries.extend(self._site_targeted())
        return queries

    def _primary_open(self) -> list[SearchQuery]:
        """Primary search prompt — open web."""
        q = f'{self._inurl_clause}"{self.sub_name}" {self.search_prompt} {self.platform} influencers list {self.year}'
        return [SearchQuery(query=q, query_type=QueryType.PRIMARY_OPEN)]

    def _alt_open(self) -> list[SearchQuery]:
        """All alt search terms — open web with region."""
        return [
            SearchQuery(
                query=f'{self._inurl_clause}"{self.sub_name}" {term} {self.platform} influencers {self.region} {self.year}',
                query_type=QueryType.ALT_OPEN,
            )
            for term in self.alt_search_terms
        ]

    def _site_targeted(self) -> list[SearchQuery]:
        """site:{source} queries — one per known source, using primary search prompt."""
        return [
            SearchQuery(
                query=f"site:{source} {self._inurl_clause}{self.search_prompt} {self.platform} {self.year}",
                query_type=QueryType.SITE_TARGETED,
            )
            for source in self.known_sources
        ]
