"""
SearchClient protocol — defines the contract for search backends.

Each client owns query building + execution for a SeedJob.
SearchService applies filtering on top of any client's raw results.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Protocol, runtime_checkable

from config.seed_schema import SeedJob


class QueryType(str, Enum):
    """Type of search query generated by a SearchClient."""
    PRIMARY_OPEN = "primary_open"
    ALT_OPEN = "alt_open"
    SITE_TARGETED = "site_targeted"


@dataclass(frozen=True)
class SearchQuery:
    """A single search query with its type for audit logging."""
    query: str
    query_type: QueryType


@dataclass(frozen=True)
class RawSearchResult:
    """Single result from a search client, before any filtering."""
    url: str
    title: str
    query: str


@runtime_checkable
class SearchClient(Protocol):
    """Protocol: owns query building + execution for one SeedJob."""

    # ── API ──
    def search(self, job: SeedJob) -> list[RawSearchResult]:
        """Build queries for job, execute them, return raw results."""
        ...

    def nr_query_template(self) -> str:
        """Return the query template for Name Resolution DDG searches.

        Template must accept `{name}` and optionally `{category}`.
        Strict (Google) uses site: scoping; Open (DDG) uses platform keywords.
        """
        ...

    def search_text(self, query: str, max_results: int = 5) -> list[dict[str, str]]:
        """Execute a free-text query and return raw result dicts.

        Each dict contains at least 'href', 'title', and optionally 'body'.
        Handles retries internally. Returns [] on permanent failure.
        Used by HandleFromNameService and NameResolver for handle lookups.
        """
        ...
