"""
Config Package
===============
Re-exports settings and schema for clean imports.

Usage:
    from config import RESULTS_DIR, GEMINI_API_KEY
    from config.schema import Influencer, PageResult
"""

from config.settings import (  # noqa: F401
    PIPELINE_ROOT, RESULTS_DIR, SEARCH_DIR, PAGES_DIR, RAW_DIR, AUDIT_DIR, REPORTS_DIR,
    GEMINI_API_KEY,
    LLM_PROVIDER, USE_OLLAMA,
    SEARCH_DELAY_SECONDS, MAX_SEARCH_RESULTS, MAX_URLS_PER_JOB,
    SEARCH_BACKEND, SEARCH_REGION,
    CRAWL_CONCURRENCY, LLM_DELAY_SECONDS, ENRICH_DELAY_SECONDS,
    MAX_RETRIES, BACKOFF_BASE_SECONDS, BACKOFF_MAX_SECONDS,
    DDG_FAILURE_THRESHOLD_PCT, DDG_FAILURE_MIN_QUERIES, DDG_KILL_AFTER_N,
    INPUT_COST_PER_1M, OUTPUT_COST_PER_1M, OUTPUT_TOKENS_PER_INFLUENCER,
    EXCLUDED_TAGS, PRUNING_THRESHOLD, WORD_COUNT_THRESHOLD,
    NAME_RESOLUTION_ENABLED, NAME_RESOLUTION_MIN_MENTIONS, NAME_RESOLUTION_MAX_PER_SUB,
    CURRENT_YEAR,
)
