"""
Canary Wiring Tests — Prove canary validation is actually called.
====================================================================

These tests verify that BasePipelineRunner.run() calls _run_canary_validation()
and populates validation_results. If someone removes the canary step from the
base template, these tests fail.
"""

import asyncio
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from config.schema import Influencer, Platform, SeedInfluencer
from config.seed_schema import SeedJob, SubCategory, Region, RegionCode, Difficulty
from base_pipeline import BasePipelineRunner, GatherResult
from services.validation.IngestionValidator import ValidationResult


# -- Fixtures --

def _make_job(
    category: str = "AI",
    sub_name: str = "AI",
    platform: Platform = Platform.Instagram,
    region_code: str = "US",
) -> SeedJob:
    sub = SubCategory(
        sub_name=sub_name,
        is_top_level=True,
        search_prompt="test",
        alt_search_terms=[],
        known_sources=[],
        platform_notes="",
        region_notes="",
        difficulty=Difficulty.EASY,
        strict_slugs=[],
    )
    region = Region(
        code=RegionCode(region_code),
        language="en",
        label="United States",
    )
    return SeedJob(
        category_key=category,
        sub=sub,
        platform=platform,
        region=region,
    )


# Known canary influencers for AI/AI/US (from canary_influencers.json)
CANARY_INFLUENCERS = [
    Influencer(name="Matt Wolfe", handles={Platform.YouTube: "mreflow"}),
    Influencer(name="Matthew Berman", handles={Platform.YouTube: "matthew_berman"}),
]


class StubRunner(BasePipelineRunner):
    """Concrete subclass for testing — returns canned GatherResult."""

    def __init__(self, gather_result: GatherResult, **kwargs):
        super().__init__(**kwargs)
        self._canned = gather_result

    async def _search_and_extract_influencers(self, jobs):
        return self._canned

    async def _on_config_search_finished(self, job, search_results):
        pass


class TestBasePipelineCanaryWiring:
    """Prove the base template calls canary validation."""

    def test_run_populates_canary_results(self):
        """After run(), validation_results should be populated for matching canaries."""
        gather = GatherResult(
            influencer_to_category=[(inf, "AI") for inf in CANARY_INFLUENCERS],
            name_tracker=None,
        )

        with tempfile.TemporaryDirectory() as tmp:
            runner = StubRunner(
                gather_result=gather,
                name_resolution=False,
            )

            jobs = [
                _make_job(category="AI", sub_name="AI", platform=Platform.Instagram),
                _make_job(category="AI", sub_name="AI", platform=Platform.YouTube),
            ]

            with (
                patch("base_pipeline.AUDIT_DIR", Path(tmp)),
                patch("base_pipeline.PipelineReporter") as MockReporter,
                patch("base_pipeline.ResultAssembler") as MockAssembler,
            ):
                MockReporter.return_value = MagicMock()
                MockAssembler.return_value = MagicMock()
                runner._assembler = MockAssembler.return_value

                seeds = asyncio.run(runner.run(jobs))

            # Canary validation should have been called
            assert runner.validation_results, (
                "Expected validation_results to be populated after run(). "
                "If empty, _run_canary_validation() was not called."
            )

            canary_key = "AI_AI_US"
            assert canary_key in runner.validation_results, (
                f"Expected canary key '{canary_key}' in results. "
                f"Got: {list(runner.validation_results.keys())}"
            )

            vr = runner.validation_results[canary_key]
            assert vr is not None
            assert vr.pass_rate == 1.0, (
                f"Expected 100% canary pass rate, got {vr.pass_rate:.0%}. "
                f"Missing: {vr.missing}"
            )

    def test_run_report_includes_canary_section(self):
        """The report generated by run() should include canary results."""
        gather = GatherResult(
            influencer_to_category=[(inf, "AI") for inf in CANARY_INFLUENCERS],
            name_tracker=None,
        )

        with tempfile.TemporaryDirectory() as tmp:
            runner = StubRunner(
                gather_result=gather,
                name_resolution=False,
            )
            jobs = [_make_job()]

            with (
                patch("base_pipeline.AUDIT_DIR", Path(tmp)),
                patch("base_pipeline.PipelineReporter") as MockReporter,
                patch("base_pipeline.ResultAssembler") as MockAssembler,
            ):
                mock_reporter_instance = MagicMock()
                MockReporter.return_value = mock_reporter_instance
                MockAssembler.return_value = MagicMock()
                runner._assembler = MockAssembler.return_value

                asyncio.run(runner.run(jobs))

            # Reporter.generate() should have been called with non-empty validation_results
            call_kwargs = mock_reporter_instance.generate.call_args
            passed_validation = call_kwargs.kwargs.get("validation_results", {})
            assert passed_validation, (
                "PipelineReporter.generate() was called with empty validation_results. "
                "Canary results should have been passed to the report."
            )

    def test_both_runners_have_search_and_extract(self):
        """Both PipelineRunner and PhasePipelineRunner inherit from BasePipelineRunner."""
        from pipeline import PerJobPipelineRunner
        from phase_pipeline import PhasePipelineRunner

        assert issubclass(PerJobPipelineRunner, BasePipelineRunner)
        assert issubclass(PhasePipelineRunner, BasePipelineRunner)
        assert hasattr(PerJobPipelineRunner, "_search_and_extract_influencers")
        assert hasattr(PhasePipelineRunner, "_search_and_extract_influencers")
        assert hasattr(PerJobPipelineRunner, "run")
        assert hasattr(PhasePipelineRunner, "run")
